# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
gem "rubocop", "~> 1.21"
gem "dry-types", '~> 1.7', '>= 1.7.2'
gem "dry-struct", '~> 1.6'
