source "https://rubygems.org"

gemspec

gem "dry-struct", "~> 1.6"
gem "dry-types", "~> 1.7", ">= 1.7.2"
gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
gem "rubocop", "~> 1.21"
gem "rubocop-rake", "~> 0.6.0"
gem "rubocop-rspec", "~> 3.3"

gem "yard", "~> 0.9.37"
