#!/usr/bin/env bash

set -euo pipefail

export PATH="/.pulumi/bin:$PATH"
export PULUMI_ACCESS_TOKEN="$(buildkite-agent secret get PULUMI_ACCESS_TOKEN)"

eval "$(pulumi env open cnunciato/default/personal --format shell)"
